module.exports = {
  LinkedIn: {
    joinNowBtnLabel: "a.nav__button-tertiary",
    signInBtnLabel: "a.nav__button-secondary",
    mainHeading: "h1.main-heading",
    emailPhoneNumberInputLabel: '.input__label[for="session_key"]',
    passwordLabel: '.input__label[for="session_password"]',
    forgetPasswordLabel: "a.sign-in-form__forgot-password-link",
    continueBtn: "#join-form-submit",
    errorlabels: ".artdeco-inline-feedback__message",
    InputField: (name) => `.input__input[name=${name}]`,
  },
  ecommerce: {
    menuitem: (item) => `//span[text()='${item}']`,
    dropdown_item: (item) => `//a[text()='${item}']`,
    title_heading: `#content>h1`,
    title_desc: "#content > p",
    desc_heading: "#account > legend",
    register_fields: (name) => `.control-label[for='input-${name}']`,
    register_inputs: (name) => `input[name='${name}']`,
    actionBtn: (action) => `input[type='${action}']`,
    continueBtn: ".pull-right > a",
    loginScreen: ".well > h2",
    loginElements: "#content>h2",
    itemsList: (item) => `//h4//a[text()='${item}']`,
    itemHeading: ".col-sm-4 > h1",
    addToCartBtn: "#button-cart",
    addToFavBtn: (button) => `button[data-original-title='${button}']`,
    favSuccess: ".alert-success",
    wishListNavLink: ".list-inline > li > a#wishlist-total",
    cartNavLink: ".list-inline > li > a[title='Shopping Cart']",
    homeBtn: ".breadcrumb > li >a >i",
    removeBtn: ".btn-danger",
    itemRemoveBtn: ".input-group-btn > button.btn-danger",
  },
};
