module.exports = {
  Amazon: {
    searchBar: `//input[@id='twotabsearchtextbox']`,
    menuItems: (i) => `//a[contains(text(),'${i}')]`,
    searchBtn: `//input[@id='nav-search-submit-button']`,
    FilterTitle: `//span[contains(text(),'Filter by price')]`,
    product_title_selector: `//span[contains(@class, 'a-size-medium a-color-base a-text-normal')]`,
    product_title: (i) => `//span[contains(text(),'${i}')]`,
    cartCount: `//span[@id='nav-cart-count']`,
    cartBtn: `//*[@class='nav-cart-icon nav-sprite']`,
    addToCartBtn: `//input[@id='add-to-cart-button']`,
    buyNowBtn: `//input[@id='buy-now-button']`,
    checkoutBtn: `//input[@value='Proceed to checkout']`,
    closeBtn: `//a[@id='attach-close_sideSheet-link']`,
    proceedToCheckout: `//button[contains(text(),'Proceed to checkout')]`,
    doneBtn: `//span[contains(text(),'DONE')]`,
    loginAction: (i) => `//span[contains(text(),'${i}')]`,
    NoAccountFound: `//h4[contains(text(),'No account found with that Email address')]`,
    EmailOrPhoneLabel: `//label[contains(text(),'Email or phone number')]`,
    inputFieldEmailSignIn: `//input[@id='ap_email']`,
    SignInLabel: `//h1[contains(text(),'Sign in')]`,
    title_text: (i) => `//label[contains(text(),'${i}')]`,
    continueBtn: (i) => `//input[@id='${i}']`,
    homeSignIn: `//span[@id='nav-link-accountList-nav-line-1']`,
    invalidCredentials_title: `//h4[contains(text(),'There was a problem')]`,
    invalidCredentials_desc: (i) => `//span[contains(text(),'${i}')]`,
    hamburger: `//a[@id='nav-hamburger-menu']`,
    Hamburger_Items: (i) => `//*[@class='hmenu-item'][contains(text(),'${i}')]`,
    Account_Title: (i) => `//h1[contains(text(),'${i}')]`,
    card_Title: (i) => `//h2[contains(text(),'${i}')]`,
    hello_title: `//span[@id='glow-ingress-line1']`,
  },
};
